apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluence-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confluence-prod
  template:
    metadata:
      labels:
        app: confluence-prod
    spec:
      containers:
      - name: confluence-prod
        image: atlassian/confluence-server
        env:
        - name: JVM_MAXIMUM_MEMORY
          value: "7000m"
        ports:
        - containerPort: 8090
        resources:
          limits:
            cpu: "2"
            memory: "8000Mi"
          requests:
            cpu: "2"
            memory: "8000Mi"
        volumeMounts:
        - name: confluence-data
          mountPath: /var/atlassian/application-data/confluence
        livenessProbe:
          httpGet:
            path: /index.html
            port: 8090
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 300
      volumes:
      - name: home
        persistentVolumeClaim:
          claimName: confluence-prod-home-claim  
      - name: confluence-libs
        persistentVolumeClaim:
          claimName: confluence-libs-claim
  volumeClaimTemplates:
  - metadata:
      name: confluence-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 25Gi

---
apiVersion: v1
kind: Service
metadata:
  name: confluence-prod-loadbalancer
spec:
  selector:
    app: confluence-prod
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8090         
