apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluence-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confluence-prod
  template:
    metadata:
      labels:
        app: confluence-prod
    spec:
      containers:
      - name: confluence-prod
        image: atlassian/confluence-server
        env:
        - name: JVM_MAXIMUM_MEMORY
          value: "7000m"
        ports:
        - containerPort: 8090
        resources:
          limits:
            cpu: "2"
            memory: "8000Mi"
          requests:
            cpu: "2"
            memory: "8000Mi"
        volumeMounts:
        - name: home
          mountPath: /var/atlassian/application-data/confluence
        - name: confluence-libs
          mountPath: /opt/atlassian/confluence/confluence/WEB-INF/lib  
        livenessProbe:
          httpGet:
            path: /index.html
            port: 8090
          initialDelaySeconds: 300
          periodSeconds: 30
      volumes:
      - name: home
        persistentVolumeClaim:
          claimName: confluence-prod-home-claim  
      - name: confluence-libs
        persistentVolumeClaim:
          claimName: confluence-libs-claim

---
apiVersion: v1
kind: Service
metadata:
  name: confluence-prod-loadbalancer
spec:
  selector:
    app: confluence-prod
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8090         
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: confluence-prod-home
  labels:
    name: confluence-prod-home
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 25Gi
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 10.102.191.21
    path: /confluence
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: confluence-libs
  labels:
    name: confluence-libs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 25Gi
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 10.102.191.21
    path: /confluence-libs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confluence-prod-home-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: "confluence-prod-home"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confluence-libs-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: "confluence-libs"      
