apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: confluence-prod
spec:
  serviceName: confluence-prod-loadbalancer
  replicas: 1
  selector:
    matchLabels:
      app: confluence-prod
  template:
    metadata:
      labels:
        app: confluence-prod
    spec:
      containers:
        - name: confluence-prod
          image: atlassian/confluence-server
          env:
            - name: JVM_MAXIMUM_MEMORY
              value: "7000m"
          ports:
            - containerPort: 443
          resources:
            limits:
              cpu: "2"
              memory: "8000Mi"
            requests:
              cpu: "2"
              memory: "8000Mi"
          volumeMounts:
            - name: confluence-data
              mountPath: /var/atlassian/application-data/confluence
          livenessProbe:
            httpGet:
              path: /
              port: 8090
            initialDelaySeconds: 300
            periodSeconds: 300
            timeoutSeconds: 300
  volumeClaimTemplates:
  - metadata:
      name: confluence-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 25Gi
---
apiVersion: v1
kind: Service
metadata:
  name: confluence-prod-loadbalancer
spec:
  selector:
    app: confluence-prod
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: confluence-prod-nodeport
spec:
  selector:
    app: confluence-prod
  type: NodePort
  ports:
    - port: 80
      targetPort: 8090
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: confluence-prod-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: confluence-public
    networking.gke.io/managed-certificates: confluence-certificate
    kubernetes.io/ingress.allow-http: "false"
spec:
  backend:
    serviceName: confluence-prod-nodeport
    servicePort: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: confluence-certificate
spec:
  domains:
    - confluence.cit326.com
